@baseUrl = https://api.themoviedb.org/3
@apiKey = 24e9e767b7d82e9d74acb843dea1960d

### Search movies
GET {{baseUrl}}/search/movie?api_key={{apiKey}}&query=Jack%20Reacher
Accept: application/json

### Get movie cast
GET {{baseUrl}}/movie/343611/credits?api_key={{apiKey}}
Accept: application/json
