export { fetchAPI } from '../api/client';
export * from './genres';
export * from './trending';
export * from './popular';
export * from './topRated';
export * from './nowPlaying';
export * from './details';
export * from './search';
export * from './tvSeason';
export * from './discover';
